#!/usr/bin/env python3
"""Hardware campaign for rizzo-flow on this machine (Linux + RTX PRO 4000 Blackwell + 9950X3D).

Runs every planned test strictly one after the other, records telemetry around each run
(Prometheus/DCGM at 1 s, node_exporter at 2 s, nvidia-smi at 100 ms, rusage of the child),
extracts the statistics from each tool's own output and, after every run, rewrites:

  - the "Results log" section of HARDWARE-REPORT-RESEARCH.md (internal notes), and
  - HARDWARE-REPORT-PR.md (paste-ready public report: no hostnames, no serials).

Resumable: finished runs are kept in ledger.json and skipped; a run interrupted half-way is
moved aside and repeated.

  python .research/hw-campaign/run_campaign.py --dry-run         # print the plan
  python .research/hw-campaign/run_campaign.py --only T0,T2       # subset (substring of id)
  python .research/hw-campaign/run_campaign.py                    # everything still to do
  python .research/hw-campaign/run_campaign.py --render           # rewrite the md files only
"""

import argparse
import csv
import json
import math
import os
import platform
import re
import shutil
import signal
import subprocess
import time
import urllib.parse
import urllib.request
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CAMPAIGN = ROOT / ".research" / "hw-campaign"
OUT = ROOT / "results" / "local-hw"
LEDGER = CAMPAIGN / "ledger.json"
RESEARCH_MD = ROOT / "HARDWARE-REPORT-RESEARCH.md"
PR_MD = ROOT / "HARDWARE-REPORT-ISSUE.md"  # paste-ready body for a GitHub issue
PR_SUMMARY = CAMPAIGN / "pr-summary.md"  # optional hand-written text, inserted in the PR file
PR_NOTES = CAMPAIGN / "pr-notes.md"  # optional hand-written notes for "Anything odd"
VENV = ROOT / ".venv" / "bin"
SEMIF = ROOT / ".research" / "SemIf"
TYPED = ROOT / ".research" / "typed-decisions" / "all" / "test.jsonl"
RUNTIMES = ROOT / "runtimes"

PROM = "http://prometheus.gio.lan:9090"
DCGM = 'hostname="pcgio"'
NODE = 'instance="pcgio:9100"'
ISSUE_TITLE = ("First Linux + NVIDIA run: RTX PRO 4000 Blackwell (CUDA, Vulkan) and Ryzen 9 9950X3D "
               "CPU-only numbers (4B and 1.7B, all quantizations and KV cache types)")
RAM_DETAIL = ("2 × 32 GB DDR5 Crucial Pro CP32G64C40U5B (DDR5-5600 CL40 modules) configured at "
              "6000 MT/s, dual channel")
AMBIENT = "29 °C at the start of the campaign (room, measured by hand); GPU board power cap 145 W"
BASELINE_S = 10
SETTLE_S = 3  # let the last 1 s / 2 s scrapes land before querying

MARK_BEGIN = "<!-- RESULTS:BEGIN (auto-generated by .research/hw-campaign/run_campaign.py) -->"
MARK_END = "<!-- RESULTS:END -->"

WEIGHTS = [("4b", "q8_0"), ("4b", "bf16"), ("4b", "q4_k_m"),
           ("1.7b", "q8_0"), ("1.7b", "q4_k_m"), ("1.7b", "bf16")]
GGUF = {
    ("4b", "q8_0"): "models/Spark-X2.5-4B-GGUF/Spark-X2.5-4B-Q8_0.gguf",
    ("4b", "q4_k_m"): "models/Spark-X2.5-4B-GGUF/Spark-X2.5-4B-Q4_K_M.gguf",
    ("4b", "bf16"): "models/Spark-X2.5-4B-GGUF/Spark-X2.5-4B.gguf",
    ("1.7b", "q8_0"): "models/Spark-X2.5-1.7B-GGUF/Spark-X2.5-1.7B-Q8_0.gguf",
    ("1.7b", "q4_k_m"): "models/Spark-X2.5-1.7B-GGUF/Spark-X2.5-1.7B-Q4_K_M.gguf",
    ("1.7b", "bf16"): "models/Spark-X2.5-1.7B-GGUF/Spark-X2.5-1.7B.gguf",
}
# Maintainers' published llama.cpp runs (Windows 10 + RTX 5060 Ti), for semif_report --against.
PUBLISHED = {
    ("cuda", "4b", "q8_0"): "results/semif-compare/rizzo-q8_0-v3-llama-cuda",
    ("cuda", "4b", "bf16"): "results/semif-compare/rizzo-bf16-v3-llama-cuda",
    ("cuda", "4b", "q4_k_m"): "results/semif-compare/rizzo-q4_k_m-v3-llama-cuda",
    ("cuda", "1.7b", "q8_0"): "results/semif-compare/rizzo-1.7b-q8_0-v3-llama-cuda",
    ("vulkan", "4b", "q8_0"): "results/semif-compare/rizzo-q8_0-v3-llama-vulkan",
}
REFERENCE_SEMIF = [  # README / results/README.md, llama.cpp, prompt v3, Win10 + RTX 5060 Ti
    ("4B Q8_0 CUDA", "0.812", "0.848", "0.793 / 0.861", "49 / 52", "20.99 / 2.60", "13/777", "5.6 GiB"),
    ("4B BF16 CUDA", "0.829", "0.859", "0.824 / 0.875", "60 / 63", "17.75 / 1.97", "1/777", "9.3 GiB"),
    ("4B Q4_K_M CUDA", "0.769", "0.835", "0.730 / 0.801", "51 / 54", "19.98 / 2.39", "2/63", "3.9 GiB"),
    ("4B Q8_0 Vulkan", "0.807", "0.854", "0.781 / 0.861", "90 / 94", "14.84 / 1.74", "0/63", "6.0 GiB"),
    ("1.7B Q8_0 CUDA", "0.678", "0.640", "0.690 / 0.514", "25 / 27", "31.59 / 5.51", "31/777", "2.3 GiB"),
]

# Rough duration estimates (seconds) for the 4B Q8_0, used only for the ETA.
EST = {
    "gpu": {"T3": 45, "T4": 25, "T5": 20, "T6": 60, "T7": 90, "T7d37": 360, "T7s": 60, "T9": 100},
    "cpu": {"T3": 60, "T4": 60, "T5": 30, "T6": 120, "T7": 1140, "T7d37": 1140, "T7s": 660,
            "T9": 1200},
}
MULT = {
    "gpu": {("4b", "q8_0"): 1, ("4b", "bf16"): 1.2, ("4b", "q4_k_m"): 1,
            ("1.7b", "q8_0"): .6, ("1.7b", "q4_k_m"): .6, ("1.7b", "bf16"): .7},
    "cpu": {("4b", "q8_0"): 1, ("4b", "bf16"): 1.4, ("4b", "q4_k_m"): 1.15,
            ("1.7b", "q8_0"): .5, ("1.7b", "q4_k_m"): .55, ("1.7b", "bf16"): .7},
}
SUITE_NAMES = {
    "T0": "unit tests", "T1": "integration tests", "T2": "rizzo devices",
    "T3": "rizzo decide examples", "T4": "smoke", "T5": "perturbations",
    "T6": "validate_checkpoint", "T7": "semif_compare", "T9": "typed-decisions",
}


# ----------------------------------------------------------------------------- plan

def plan():
    runs = []

    def add(run):
        run.setdefault("kv", None)
        run.setdefault("extra", {})
        runs.append(run)

    add({"id": "T0-unit", "block": "one-off", "suite": "T0", "device": None})
    for pkg in ("cuda", "cpu", "vulkan"):
        add({"id": f"T2-devices-{pkg}", "block": "one-off" if pkg != "vulkan" else "vulkan",
             "suite": "T2", "device": None, "package": pkg})
    add({"id": "T1-integration", "block": "one-off", "suite": "T1", "device": None})
    # The suite loads the smallest Q8_0 on disk (the 1.7B here); repeat it pinned to the 4B.
    add({"id": "T1-integration-4b", "block": "one-off", "suite": "T1", "device": None,
         "pin_4b": True})

    def config_runs(device, size, quant, block, suites, kv=None, extra=None):
        for suite in suites:
            kvname = kv or "f16"
            ex = dict(extra or {})
            if suite == "T7" and device == "cuda" and size == "4b" and quant in ("q8_0", "bf16") \
                    and kv is None:
                ex["direct_states"] = 37  # comparable with the published 13/777 and 1/777
            add({"id": f"{device}-{size}-{quant}-{kvname}-{suite}", "block": block,
                 "suite": suite, "device": device, "size": size, "quant": quant, "kv": kv,
                 "extra": ex})

    core = ["T3", "T4", "T5", "T6", "T7", "T9"]
    for size, quant in WEIGHTS:
        config_runs("cuda", size, quant, "core", core)
    for size, quant in WEIGHTS:
        for kv in ("q8_0", "q4_0"):
            config_runs("cuda", size, quant, "kv", ["T4", "T7"], kv=kv)
    add({"id": "vulkan-4b-q8_0-f16-T4", "block": "vulkan", "suite": "T4", "device": "vulkan",
         "size": "4b", "quant": "q8_0"})
    add({"id": "vulkan-4b-q8_0-f16-T7", "block": "vulkan", "suite": "T7", "device": "vulkan",
         "size": "4b", "quant": "q8_0", "extra": {"direct_states": 37}})
    for batch in (1, 2, 4, 8, 16):
        add({"id": f"cuda-4b-q8_0-f16-T7-batch{batch}", "block": "sweep", "suite": "T7",
             "device": "cuda", "size": "4b", "quant": "q8_0",
             "extra": {"batch_size": batch, "direct_states": 0}})
    # CPU block: threads first (llama.cpp defaults to 4 threads when --threads is unset),
    # then everything else with the fastest thread count found here.
    for threads in (None, 16, 32):
        add({"id": f"cpu-4b-q8_0-f16-T4-threads{threads or 'default'}", "block": "sweep",
             "suite": "T4", "device": "cpu", "size": "4b", "quant": "q8_0",
             "extra": {"threads": threads or "none"}})
    for size, quant in WEIGHTS:
        config_runs("cpu", size, quant, "core", core)
    for size, quant in WEIGHTS:
        for kv in ("q8_0", "q4_0"):
            config_runs("cpu", size, quant, "kv", ["T4", "T7"], kv=kv)
    for batch in (1, 2, 4, 8, 16):
        add({"id": f"cpu-4b-q8_0-f16-T7-batch{batch}", "block": "sweep", "suite": "T7",
             "device": "cpu", "size": "4b", "quant": "q8_0",
             "extra": {"batch_size": batch, "direct_states": 0}})
    ids = [r["id"] for r in runs]
    assert len(ids) == len(set(ids)), "duplicate run ids"
    return runs


def dev_class(run):
    return "cpu" if run.get("device") == "cpu" else "gpu"


def estimate(run):
    suite = run["suite"]
    if suite in ("T0", "T1", "T2"):
        return {"T0": 10, "T1": 90, "T2": 5}[suite]
    cls = dev_class(run)
    key = suite
    if suite == "T7":
        ds = run["extra"].get("direct_states")
        key = "T7d37" if ds == 37 else "T7s" if ds == 0 else "T7"
    base = EST[cls][key] * MULT[cls][(run["size"], run["quant"])]
    if run["device"] == "vulkan":
        base *= 1.6
    return base + BASELINE_S + SETTLE_S


# ----------------------------------------------------------------------------- ledger

def load_ledger():
    if LEDGER.exists():
        return json.loads(LEDGER.read_text(encoding="utf-8"))
    return {"runs": {}}


def save_ledger(ledger):
    tmp = LEDGER.with_suffix(".tmp")
    tmp.write_text(json.dumps(ledger, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(LEDGER)


def cpu_threads(ledger):
    """Fastest of the explicit thread counts on the CPU smoke sweep (median latency)."""
    best = None
    for threads in (16, 32):
        rec = ledger["runs"].get(f"cpu-4b-q8_0-f16-T4-threads{threads}")
        median = g(rec, "stats.latency_median_s") if rec else None
        if median is not None and (best is None or median < best[1]):
            best = (threads, median)
    return best[0] if best else 16


# ----------------------------------------------------------------------------- commands

def model_args(run):
    args = ["--size", run["size"], "--quant", run["quant"], "--device", run["device"]]
    if run.get("kv"):
        args += ["--kv-type", run["kv"]]
    return args


def commands(run, rundir, ledger):
    """List of (argv, env_extra, label)."""
    suite, ex = run["suite"], run["extra"]
    rizzo, py = str(VENV / "rizzo"), str(VENV / "python")
    threads = []
    if run.get("device") == "cpu":
        t = ex.get("threads")
        if t == "none":
            threads = []
        elif t:
            threads = ["--threads", str(t)]
        else:
            threads = ["--threads", str(cpu_threads(ledger))]
    if suite == "T0":
        return [([str(VENV / "pytest"), "-q"], {}, "pytest")]
    if suite == "T1":
        if run.get("pin_4b"):
            return [([str(VENV / "pytest"), "-q", "-m", "integration", "-p", "pin_4b_plugin"],
                     {"RIZZO_REAL": "1", "PYTHONPATH": str(CAMPAIGN)}, "pytest")]
        return [([str(VENV / "pytest"), "-q", "-m", "integration"], {"RIZZO_REAL": "1"}, "pytest")]
    if suite == "T2":
        pkg = RUNTIMES / f"llama-b11081-linux-x64-{run['package']}"
        return [([rizzo, "devices"], {"RIZZO_LLAMA_DIR": str(pkg)}, "devices")]
    if suite == "T3":
        return [([rizzo, "decide", f"examples/{name}.json", *model_args(run), *threads,
                  "--output", str(rundir / f"decide-{name}.json")], {}, name)
                for name in ("ticket", "house", "numeric")]
    if suite in ("T4", "T5"):
        bench = "smoke" if suite == "T4" else "perturbations"
        return [([rizzo, "evaluate", f"benchmarks/{bench}.jsonl", "--compare-modes",
                  *model_args(run), *threads, "--output", str(rundir / f"{bench}.json")],
                 {}, bench)]
    # The scripts have no --threads flag: on the CPU a wrapper injects the thread count.
    script_env = {"RIZZO_HW_THREADS": threads[1]} if threads else {}
    script = [py, str(CAMPAIGN / "threads_wrapper.py")] if threads else [py]
    if suite == "T6":
        # validate_checkpoint.py has no --kv-type flag either.
        return [([*script, "scripts/validate_checkpoint.py", "--size", run["size"], "--quant",
                  run["quant"], "--device", run["device"], "--output", str(rundir / "validate")],
                 script_env, "validate")]
    if suite == "T7":
        argv = [*script, "scripts/semif_compare.py", "--system", "rizzo", "--semif", str(SEMIF),
                *model_args(run), "--output", str(rundir / "semif")]
        if "batch_size" in ex:
            argv += ["--batch-size", str(ex["batch_size"])]
        if "direct_states" in ex:
            argv += ["--direct-states", str(ex["direct_states"])]
        return [(argv, script_env, "semif")]
    if suite == "T9":
        argv = [*script, "scripts/typed_decisions.py", str(TYPED), "--model",
                str(ROOT / GGUF[(run["size"], run["quant"])]), "--device", run["device"],
                "--output", str(rundir / "typed.json")]
        return [(argv, script_env, "typed")]
    raise ValueError(suite)


def post_commands(run, rundir, ledger):
    """Commands run after the timed window (no telemetry): semif_report for held-out numbers."""
    if run["suite"] != "T7" or not (rundir / "semif" / "report.json").exists():
        return []
    argv = [str(VENV / "python"), "scripts/semif_report.py", str(rundir / "semif"),
            "--semif", str(SEMIF)]
    # Compare like with like: the maintainers' runs all use the default (f16) KV cache.
    pub = PUBLISHED.get((run["device"], run["size"], run["quant"]))
    if pub and (ROOT / pub).exists() and not run.get("kv") and "batch_size" not in run["extra"]:
        argv += ["--against", f"maintainers={ROOT / pub}"]
    baselines = []
    if run.get("kv"):  # KV effect alone: same device, same weights, f16 KV
        baselines.append((f"this-{run['device']}-kv-f16",
                          OUT / f"{run['device']}-{run['size']}-{run['quant']}-f16-T7" / "semif"))
    elif run["device"] != "cuda" and "batch_size" not in run["extra"]:  # device effect alone
        baselines.append(("this-cuda", OUT / f"cuda-{run['size']}-{run['quant']}-f16-T7" / "semif"))
    for name, ours in baselines:
        if (ours / "report.json").exists() and ours != rundir / "semif":
            argv += ["--against", f"{name}={ours}"]
    return [(argv, {}, "semif_report")]


# ----------------------------------------------------------------------------- telemetry

def prom(query, at):
    url = f"{PROM}/api/v1/query?" + urllib.parse.urlencode({"query": query, "time": f"{at:.3f}"})
    try:
        with urllib.request.urlopen(url, timeout=10) as response:
            data = json.load(response)["data"]["result"]
        return float(data[0]["value"][1]) if data else None
    except Exception:  # Prometheus down: telemetry is optional
        return None


def prometheus_stats(t0, t1, b0, b1):
    """DCGM (1 s) and node_exporter (2 s) over the run window, never padded before t0.
    Runs shorter than 5 s get no DCGM averages (too few samples): use the nvidia-smi figures."""
    if t1 - t0 < 5:
        return {"window_s": t1 - t0, "short_window": True}
    d = math.floor(t1 - t0)
    bd = max(2, math.floor(b1 - b0))
    w = f"[{d}s]"
    energy = None
    e0 = prom(f"DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{{{DCGM}}}", t0)
    e1 = prom(f"DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{{{DCGM}}}", t1)
    if e0 is not None and e1 is not None:
        energy = (e1 - e0) / 1e3
    s = {
        "gpu_power_avg_w": prom(f"avg_over_time(DCGM_FI_DEV_POWER_USAGE{{{DCGM}}}{w})", t1),
        "gpu_power_max_w": prom(f"max_over_time(DCGM_FI_DEV_POWER_USAGE_INSTANT{{{DCGM}}}{w})", t1),
        "gpu_energy_j": energy,
        "gpu_fb_used_max_mib": prom(f"max_over_time(DCGM_FI_DEV_FB_USED{{{DCGM}}}{w})", t1),
        "gpu_util_avg_pct": prom(f"avg_over_time(DCGM_FI_DEV_GPU_UTIL{{{DCGM}}}{w})", t1),
        "gpu_sm_active_avg": prom(f"avg_over_time(DCGM_FI_PROF_SM_ACTIVE{{{DCGM}}}{w})", t1),
        "gpu_dram_active_avg": prom(f"avg_over_time(DCGM_FI_PROF_DRAM_ACTIVE{{{DCGM}}}{w})", t1),
        "gpu_temp_max_c": prom(f"max_over_time(DCGM_FI_DEV_GPU_TEMP{{{DCGM}}}{w})", t1),
        "gpu_sm_clock_avg_mhz": prom(f"avg_over_time(DCGM_FI_DEV_SM_CLOCK{{{DCGM}}}{w})", t1),
        "gpu_power_cap_throttle_s": _div(prom(
            f"increase(DCGM_FI_DEV_CLOCKS_EVENT_REASON_SW_POWER_CAP_NS{{{DCGM}}}{w})", t1), 1e9),
        "gpu_thermal_throttle_s": _div(prom(
            f"increase(DCGM_FI_DEV_CLOCKS_EVENT_REASON_HW_THERM_SLOWDOWN_NS{{{DCGM}}}{w})", t1), 1e9),
        "cpu_util_avg": prom(
            f"1 - avg(rate(node_cpu_seconds_total{{{NODE},mode=\"idle\"}}{w}))", t1),
        "baseline_gpu_power_w": prom(
            f"avg_over_time(DCGM_FI_DEV_POWER_USAGE{{{DCGM}}}[{bd}s])", b1),
        "baseline_gpu_util_pct": prom(f"avg_over_time(DCGM_FI_DEV_GPU_UTIL{{{DCGM}}}[{bd}s])", b1),
        "baseline_fb_used_mib": prom(f"avg_over_time(DCGM_FI_DEV_FB_USED{{{DCGM}}}[{bd}s])", b1),
        "window_s": t1 - t0,
    }
    if s["gpu_energy_j"] is not None and s["baseline_gpu_power_w"] is not None:
        s["gpu_net_energy_j"] = s["gpu_energy_j"] - s["baseline_gpu_power_w"] * (t1 - t0)
    return s


def _div(value, by):
    return None if value is None else value / by


class Sampler:
    FIELDS = ["timestamp", "utilization.gpu", "memory.used", "power.draw.instant",
              "temperature.gpu", "clocks.sm", "clocks_event_reasons.active"]

    def __init__(self, path):
        self.path = path
        self.stream = open(path, "w", encoding="utf-8")
        self.proc = subprocess.Popen(
            ["nvidia-smi", f"--query-gpu={','.join(self.FIELDS)}", "--format=csv,noheader,nounits",
             "-lms", "100"], stdout=self.stream, stderr=subprocess.DEVNULL)

    def stop(self):
        self.proc.send_signal(signal.SIGINT)
        try:
            self.proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            self.proc.kill()
        self.stream.close()

    def summary(self, t0, t1, b0, b1):
        rows = []
        with open(self.path, encoding="utf-8") as stream:
            for rec in csv.reader(stream):
                if len(rec) < 6:
                    continue
                try:
                    ts = datetime.strptime(rec[0].strip(), "%Y/%m/%d %H:%M:%S.%f").timestamp()
                    rows.append((ts, _num(rec[1]), _num(rec[2]), _num(rec[3]), _num(rec[4])))
                except ValueError:
                    continue
        run = [r for r in rows if t0 <= r[0] <= t1]
        base = [r for r in rows if b0 <= r[0] <= b1]

        def agg(sel, i, fn):
            vals = [r[i] for r in sel if r[i] is not None]
            return fn(vals) if vals else None

        mean = lambda v: sum(v) / len(v)  # noqa: E731
        energy = 0.0
        powered = [(r[0], r[3]) for r in run if r[3] is not None]
        for (ta, pa), (tb, pb) in zip(powered, powered[1:]):
            energy += (pa + pb) / 2 * (tb - ta)
        if powered:  # edges: extend the first/last reading to t0/t1
            energy += powered[0][1] * (powered[0][0] - t0) + powered[-1][1] * (t1 - powered[-1][0])
        base_power = agg(base, 3, mean)
        return {
            "energy_j": energy if powered else None,
            "net_energy_j": energy - base_power * (t1 - t0) if powered and base_power else None,
            "samples": len(run),
            "mem_used_max_mib": agg(run, 2, max),
            "mem_used_baseline_mib": agg(base, 2, mean),
            "util_avg_pct": agg(run, 1, mean),
            "util_max_pct": agg(run, 1, max),
            "power_avg_w": agg(run, 3, mean),
            "power_max_w": agg(run, 3, max),
            "power_baseline_w": agg(base, 3, mean),
            "temp_max_c": agg(run, 4, max),
        }


def _num(text):
    try:
        return float(text.strip())
    except ValueError:
        return None


# ----------------------------------------------------------------------------- extraction

def g(obj, path, default=None):
    for key in path.split("."):
        if isinstance(obj, dict) and key in obj:
            obj = obj[key]
        else:
            return default
    return obj


def read_json(path):
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except Exception:
        return None


def model_info(model):
    if not isinstance(model, dict):
        return {}
    keys = ("device_name", "device", "backend", "precision", "kv_type", "load_seconds",
            "context_cells", "fingerprint", "llama_cpp_release")
    return {k: model.get(k) for k in keys if k in model}


def evaluate_stats(report):
    s = report.get("summary", {}) if report else {}
    rows = report.get("rows", []) if report else []
    peaks = []
    for row in rows:
        for resp in (row.get("response"), row.get("alternate_mode_response")):
            p = g(resp, "timing.peak_device_bytes")
            if p:
                peaks.append(p)
    first = rows[0].get("response") if rows else None
    return {
        "requests": s.get("requests"),
        "decisions_per_second": s.get("decisions_per_second"),
        "latency_median_s": g(s, "latency_seconds.median"),
        "latency_p95_s": g(s, "latency_seconds.p95"),
        "coverage": s.get("labeled_decision_coverage"),
        "status_accuracy": s.get("status_accuracy"),
        "accuracy": g(s, "categorical.accuracy"),
        "categorical_rows": g(s, "categorical.rows"),
        "accepted_accuracy": g(s, "categorical.accepted_accuracy"),
        "nll": g(s, "categorical.nll"),
        "brier": g(s, "categorical.brier"),
        "ece": g(s, "categorical.ece_10_bins"),
        "mode_decisions": g(s, "mode_comparison.decisions"),
        "changed_argmaxes": g(s, "mode_comparison.changed_argmaxes"),
        "max_probability_delta": g(s, "mode_comparison.max_probability_delta"),
        "median_shared_s": g(s, "mode_comparison.median_seconds.shared"),
        "median_direct_s": g(s, "mode_comparison.median_seconds.direct"),
        "peak_device_bytes": max(peaks) if peaks else None,
        "model": model_info(g(first, "model")),
    }


def extract(run, rundir, outputs):
    suite = run["suite"]
    if suite in ("T0", "T1"):
        text = outputs.get("pytest", "")
        count = lambda w: int(m.group(1)) if (m := re.search(rf"(\d+) {w}", text)) else 0  # noqa
        tail = [line for line in text.strip().splitlines() if line.strip()][-1:] or [""]
        return {"passed": count("passed"), "failed": count("failed"), "skipped": count("skipped"),
                "errors": count("error"), "summary_line": tail[0].strip("= "),
                "failed_tests": re.findall(r"^FAILED (\S+)", text, re.M)}
    if suite == "T2":
        data = None
        try:
            data = json.loads(outputs.get("devices", ""))
        except ValueError:
            pass
        (rundir / "devices.json").write_text(outputs.get("devices", ""), encoding="utf-8")
        sec = (data or {}).get("llama.cpp") or {}
        return {"directory": Path(sec.get("directory", "")).name, "devices": sec.get("devices"),
                "auto_selects": sec.get("auto_selects"), "installed": sec.get("installed"),
                "error": sec.get("error"), "raw": data}
    if suite == "T3":
        out = {}
        for name in ("ticket", "house", "numeric"):
            resp = read_json(rundir / f"decide-{name}.json")
            if not resp:
                continue
            answers = {}
            for qid, ans in (resp.get("answers") or {}).items():
                value = ans.get("value", ans.get("choice", ans.get("score")))
                answers[qid] = {"status": ans.get("status"), "value": value,
                                "top_probability": g(ans, "uncertainty.top_probability")}
            out[name] = {"answers": answers, "total_s": g(resp, "timing.total_seconds"),
                         "inference_s": g(resp, "timing.inference_seconds"),
                         "prefill_s": g(resp, "timing.prefill_seconds"),
                         "input_tokens": g(resp, "timing.logical_input_tokens"),
                         "peak_device_bytes": g(resp, "timing.peak_device_bytes"),
                         "model": model_info(resp.get("model"))}
        return out
    if suite in ("T4", "T5"):
        name = "smoke" if suite == "T4" else "perturbations"
        return evaluate_stats(read_json(rundir / f"{name}.json"))
    if suite == "T6":
        summary = read_json(rundir / "validate" / "summary.json") or {}
        suites = summary.get("suites", {})
        long_state = suites.get("long-state", {})
        peaks = []
        for fname in ("smoke", "perturbations", "long-state", "api-example"):
            data = read_json(rundir / "validate" / f"{fname}.json") or {}
            for row in data.get("rows", []):
                for resp in (row.get("response"), row.get("alternate_mode_response")):
                    if g(resp, "timing.peak_device_bytes"):
                        peaks.append(g(resp, "timing.peak_device_bytes"))
        return {
            "validation_s": summary.get("validation_seconds"),
            "model": model_info(summary.get("model")),
            "smoke_accuracy": g(suites, "smoke.categorical.accuracy"),
            "smoke_nll": g(suites, "smoke.categorical.nll"),
            "smoke_changed_argmaxes": g(suites, "smoke.mode_comparison.changed_argmaxes"),
            "perturbations_accuracy": g(suites, "perturbations.categorical.accuracy"),
            "long_shared_s": g(long_state, "mode_comparison.median_seconds.shared"),
            "long_direct_s": g(long_state, "mode_comparison.median_seconds.direct"),
            "long_changed_argmaxes": g(long_state, "mode_comparison.changed_argmaxes"),
            "long_max_probability_delta": g(long_state, "mode_comparison.max_probability_delta"),
            "peak_device_bytes": max(peaks) if peaks else None,
        }
    if suite == "T7":
        rep = read_json(rundir / "semif" / "report.json") or {}
        ana = read_json(rundir / "semif" / "analysis.json") or {}
        q, st, sh = rep.get("quality", {}), rep.get("stability", {}), rep.get("shape", {})
        peaks = [g(q, "authored144.peak_device_bytes"), g(q, "perturbations108.peak_device_bytes"),
                 g(sh, "shared.peak_device_bytes"), g(sh, "direct.peak_device_bytes")]
        peaks = [p for p in peaks if p]
        against = {}
        for name, block in (ana.get("against") or {}).items():
            pd = g(block, "paired_difference_ours_minus_theirs.authored144") or {}
            against[name] = {
                "held_out_authored144": g(block, "held_out.authored144"),
                "held_out_perturbations108": g(block, "held_out.perturbations108"),
                "difference_authored144": pd.get("difference"),
                "ci95_authored144": pd.get("paired_source_group_bootstrap_95"),
                "different_argmax": block.get("different_argmax"), "rows": block.get("rows"),
            }
        return {
            "model": model_info(rep.get("model")),
            "authored144": g(q, "authored144.mean_family_balanced_accuracy"),
            "perturbations108": g(q, "perturbations108.mean_family_balanced_accuracy"),
            "authored144_macro_f1": g(q, "authored144.mean_family_macro_f1"),
            "rule_application_pert_bacc": g(q, "perturbations108.families.rule_application.balanced_accuracy"),
            "rule_application_pert_nll": g(q, "perturbations108.families.rule_application.nll"),
            "p50_s": g(q, "authored144.latency.p50_seconds"),
            "p95_s": g(q, "authored144.latency.p95_seconds"),
            "flips_reversal": g(st, "variants.option_reversal.argmax_flips"),
            "flips_wrapper": g(st, "variants.criterion_wrapper.argmax_flips"),
            "flips_context": g(st, "variants.irrelevant_context.argmax_flips"),
            "missing_evidence_confident": g(st, "missing_evidence.confident_non_insufficient_at_0_8"),
            "shared_dps": g(sh, "shared.decisions_per_second"),
            "direct_dps": g(sh, "direct.decisions_per_second"),
            "shared_states": g(sh, "shared.states"),
            "direct_states": g(sh, "direct.states"),
            "shared_tokens_per_decision": g(sh, "shared.input_tokens_per_decision"),
            "sd_flips": g(sh, "shared_vs_direct.argmax_flips"),
            "sd_rows": g(sh, "shared_vs_direct.rows"),
            "sd_max_dp": g(sh, "shared_vs_direct.max_probability_difference"),
            "held_out_authored144": g(ana, "held_out.authored144"),
            "held_out_perturbations108": g(ana, "held_out.perturbations108"),
            "against": against,
            "peak_device_bytes": max(peaks) if peaks else None,
        }
    if suite == "T9":
        rep = read_json(rundir / "typed.json") or {}
        ov = g(rep, "metrics.overall") or {}
        return {
            "accuracy": ov.get("accuracy"), "kl": ov.get("kl"), "brier": ov.get("brier"),
            "ece": ov.get("ece"), "macro_f1": ov.get("macro_f1"),
            "p50_ms": g(rep, "timing.p50_ms_per_case"), "p95_ms": g(rep, "timing.p95_ms_per_case"),
            "decisions_per_second": g(rep, "timing.decisions_per_second"),
            "by_workflow": {k: v.get("accuracy") for k, v in (g(rep, "metrics.by_workflow") or {}).items()},
            "model": model_info(rep.get("model")) if isinstance(rep.get("model"), dict) else rep.get("model"),
        }
    return {}


def expected_output(run, rundir):
    if run["suite"] == "T3":
        return [rundir / f"decide-{name}.json" for name in ("ticket", "house", "numeric")]
    return {
        "T4": rundir / "smoke.json",
        "T5": rundir / "perturbations.json", "T6": rundir / "validate" / "summary.json",
        "T7": rundir / "semif" / "report.json", "T9": rundir / "typed.json",
    }.get(run["suite"])


# ----------------------------------------------------------------------------- execution

def leftover_model_processes():
    """Other processes of this checkout that may hold a model (never the runner itself)."""
    found = []
    for pid in os.listdir("/proc"):
        if not pid.isdigit() or int(pid) in (os.getpid(), os.getppid()):
            continue
        try:
            cmd = (Path("/proc") / pid / "cmdline").read_bytes().replace(b"\0", b" ").decode()
        except OSError:
            continue
        if str(VENV) in cmd and "run_campaign.py" not in cmd and any(
                k in cmd for k in ("rizzo", "scripts/", "pytest")):
            found.append(f"{pid}: {cmd[:120]}")
    return found


def execute(run, ledger):
    for _ in range(12):  # one model process at a time: wait up to 60 s, then stop
        left = leftover_model_processes()
        if not left:
            break
        time.sleep(5)
    else:
        raise SystemExit(f"another model process is running, stopping: {left}")
    rundir = OUT / run["id"]
    if rundir.exists():  # interrupted earlier: keep the evidence, start clean
        aside = OUT / "_aborted" / f"{run['id']}-{int(time.time())}"
        aside.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(rundir), str(aside))
    rundir.mkdir(parents=True)
    cmds = commands(run, rundir, ledger)
    sampler = Sampler(rundir / "nvidia-smi.csv")
    b0 = time.time()
    time.sleep(BASELINE_S)
    b1 = time.time()
    outputs, exits, cpu_s, maxrss_kib = {}, [], 0.0, 0
    started = time.strftime("%Y-%m-%d %H:%M:%S")
    t0 = time.time()
    proc = None
    try:
        for argv, env_extra, label in cmds:
            env = {**os.environ, **env_extra}
            with open(rundir / f"{label}.stdout", "w", encoding="utf-8") as out, \
                    open(rundir / f"{label}.stderr", "w", encoding="utf-8") as err:
                proc = subprocess.Popen(argv, cwd=ROOT, env=env, stdout=out, stderr=err)
                _, status, usage = os.wait4(proc.pid, 0)
                proc.returncode = os.waitstatus_to_exitcode(status)
            exits.append(proc.returncode)
            cpu_s += usage.ru_utime + usage.ru_stime
            maxrss_kib = max(maxrss_kib, usage.ru_maxrss)
            outputs[label] = (rundir / f"{label}.stdout").read_text(encoding="utf-8", errors="replace")
    finally:  # never leave a model process or the sampler behind (Ctrl-C, SIGTERM)
        if proc is not None and proc.returncode is None:
            proc.terminate()
            try:
                proc.wait(timeout=20)
            except subprocess.TimeoutExpired:
                proc.kill()
        t1 = time.time()
        sampler.stop()
    for argv, env_extra, label in post_commands(run, rundir, ledger):
        with open(rundir / f"{label}.stdout", "w", encoding="utf-8") as out, \
                open(rundir / f"{label}.stderr", "w", encoding="utf-8") as err:
            subprocess.run(argv, cwd=ROOT, env={**os.environ, **env_extra}, stdout=out, stderr=err)
    time.sleep(SETTLE_S)
    wall = t1 - t0
    exp = expected_output(run, rundir)
    if isinstance(exp, list):
        produced = all(p.exists() for p in exp)
    elif exp:
        produced = exp.exists()
    else:  # pytest: "ok" means the suite ran; failing tests are results, listed in stats
        produced = all(code == 0 for code in exits) or (
            run["suite"] in ("T0", "T1") and exits == [1]
            and re.search(r"\d+ (passed|failed)", outputs.get("pytest", "")) is not None)
    stderr_tail = []
    for _, _, label in cmds:
        lines = (rundir / f"{label}.stderr").read_text(encoding="utf-8", errors="replace").splitlines()
        stderr_tail += [f"{label}: {redact(line)}" for line in lines if line.strip()][-5:]
    record = {
        "id": run["id"], "run": run, "started": started, "wall_s": wall,
        "t0": t0, "t1": t1, "b0": b0, "b1": b1,
        "exit_codes": exits, "status": "ok" if produced else "failed",
        "commands": [" ".join(_short(a) for a in argv) for argv, _, _ in cmds],
        "threads": _threads_used(cmds),
        "env": [e for _, e, _ in cmds],
        "stats": extract(run, rundir, outputs) if produced or run["suite"] in ("T0", "T1", "T2") else {},
        "rusage": {"cpu_seconds": cpu_s, "avg_cores": cpu_s / wall if wall else None,
                   "max_rss_gib": maxrss_kib / 2**20},
        "nvidia_smi": sampler.summary(t0, t1, b0, b1),
        "prometheus": prometheus_stats(t0, t1, b0, b1),
        "stderr_tail": stderr_tail,
        "estimate_s": estimate(run),
    }
    (rundir / "metrics.json").write_text(json.dumps(record, indent=2, ensure_ascii=False),
                                         encoding="utf-8")
    return record


def redact(text):
    """Strip local paths and user names from free text that may reach the public report."""
    text = text.replace(str(VENV) + "/", "").replace(str(ROOT) + "/", "")
    text = text.replace(str(Path.home()), "~")
    return re.sub(r"/media/[^\s:'\"]*/", ".../", text)


def _threads_used(cmds):
    for argv, env, _ in cmds:
        if "RIZZO_HW_THREADS" in env:
            return int(env["RIZZO_HW_THREADS"])
        if "--threads" in argv:
            return int(argv[argv.index("--threads") + 1])
    return None


def _short(arg):
    arg = str(arg)
    for prefix, repl in ((str(VENV) + "/", ""), (str(ROOT) + "/", "")):
        if arg.startswith(prefix):
            arg = repl + arg[len(prefix):]
    return arg


# ----------------------------------------------------------------------------- rendering

def fmt(value, digits=3, unit=""):
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.{digits}f}{unit}"
    return f"{value}{unit}"


def ms(value):
    return "—" if value is None else f"{value * 1000:.0f}"


def gib(value):
    return "—" if not value else f"{value / 2**30:.2f} GiB"


def label(run):
    if run.get("device") is None:
        return run["id"]
    size = run["size"].upper()
    parts = [f"{size} {run['quant'].upper()}", run["device"].upper() if run["device"] != "vulkan"
             else "Vulkan"]
    if run.get("kv"):
        parts.append(f"KV {run['kv']}")
    ex = run.get("extra", {})
    if "batch_size" in ex:
        parts.append(f"batch {ex['batch_size']}")
    if ex.get("threads"):
        parts.append(f"threads {'default (4)' if ex['threads'] == 'none' else ex['threads']}")
    return " · ".join(parts)


def mem_cell(rec):
    peak = g(rec, "stats.peak_device_bytes")
    if rec["run"].get("device") == "cpu":
        return f"RSS {rec['rusage']['max_rss_gib']:.2f} GiB"
    return gib(peak)


def progress(ledger, runs):
    done = [ledger["runs"][r["id"]] for r in runs if r["id"] in ledger["runs"]]
    todo = [r for r in runs if r["id"] not in ledger["runs"]]
    ratio = {}
    for cls in ("gpu", "cpu"):
        act = sum(d["wall_s"] + BASELINE_S + SETTLE_S for d in done if dev_class(d["run"]) == cls
                  and d["run"]["suite"] not in ("T0", "T1", "T2"))
        est = sum(d["estimate_s"] for d in done if dev_class(d["run"]) == cls
                  and d["run"]["suite"] not in ("T0", "T1", "T2"))
        ratio[cls] = act / est if est else 1.0
    remaining = sum(estimate(r) * (ratio[dev_class(r)] if r["suite"] not in ("T0", "T1", "T2")
                                   else 1) for r in todo)
    elapsed = sum(d["wall_s"] + BASELINE_S + SETTLE_S for d in done)
    failed = sum(1 for d in done if d["status"] != "ok")
    return len(done), len(runs), failed, elapsed, remaining, ratio


def hms(seconds):
    seconds = int(seconds)
    return f"{seconds // 3600}h{seconds % 3600 // 60:02d}m"


def stats_lines(rec):
    s, suite = rec["stats"], rec["run"]["suite"]
    if suite in ("T0", "T1"):
        return [f"passed {s.get('passed')}, failed {s.get('failed')}, skipped {s.get('skipped')} "
                f"— `{s.get('summary_line')}`"]
    if suite == "T2":
        devs = ", ".join(f"{d.get('name')} ({d.get('kind')}, {d.get('description')})"
                         for d in (s.get("devices") or []))
        return [f"runtime `{s.get('directory')}`; devices: {devs or '—'}; auto_selects "
                f"`{s.get('auto_selects')}`" + (f"; error: {s['error']}" if s.get("error") else "")]
    if suite == "T3":
        out = []
        for name, d in s.items():
            ans = "; ".join(f"{q}={a['value']} ({a['status']}, p={fmt(a['top_probability'])})"
                            for q, a in d["answers"].items())
            out.append(f"{name}: {ans} — total {ms(d['total_s'])} ms, inference "
                       f"{ms(d['inference_s'])} ms, {d['input_tokens']} tokens, load "
                       f"{fmt(g(d, 'model.load_seconds'), 1)} s")
        return out
    if suite in ("T4", "T5"):
        return [f"accuracy {fmt(s.get('accuracy'))} ({s.get('categorical_rows')} rows), accepted "
                f"{fmt(s.get('accepted_accuracy'))}, coverage {fmt(s.get('coverage'))}, NLL "
                f"{fmt(s.get('nll'))}, Brier {fmt(s.get('brier'))}, ECE {fmt(s.get('ece'))}",
                f"latency median {ms(s.get('latency_median_s'))} ms, p95 "
                f"{ms(s.get('latency_p95_s'))} ms, {fmt(s.get('decisions_per_second'), 2)} dec/s",
                f"shared vs direct: {s.get('changed_argmaxes')}/{s.get('mode_decisions')} changed "
                f"argmaxes, max Δp {fmt(s.get('max_probability_delta'), 6)}, median "
                f"{ms(s.get('median_shared_s'))} / {ms(s.get('median_direct_s'))} ms",
                f"peak device {gib(s.get('peak_device_bytes'))}, device "
                f"`{g(s, 'model.device_name')}` ({g(s, 'model.backend')}), load "
                f"{fmt(g(s, 'model.load_seconds'), 1)} s"]
    if suite == "T6":
        return [f"smoke accuracy {fmt(s.get('smoke_accuracy'))} (NLL {fmt(s.get('smoke_nll'))}, "
                f"{s.get('smoke_changed_argmaxes')} changed), perturbations "
                f"{fmt(s.get('perturbations_accuracy'))}",
                f"long state: shared {ms(s.get('long_shared_s'))} ms vs direct "
                f"{ms(s.get('long_direct_s'))} ms, {s.get('long_changed_argmaxes')} changed "
                f"(max Δp {fmt(s.get('long_max_probability_delta'), 6)})",
                f"validation {fmt(s.get('validation_s'), 1)} s, load "
                f"{fmt(g(s, 'model.load_seconds'), 1)} s, peak {gib(s.get('peak_device_bytes'))}"]
    if suite == "T7":
        out = [f"authored144 {fmt(s.get('authored144'))}, perturbations108 "
               f"{fmt(s.get('perturbations108'))}, held-out {fmt(s.get('held_out_authored144'))} / "
               f"{fmt(s.get('held_out_perturbations108'))}, macro-F1 {fmt(s.get('authored144_macro_f1'))}",
               f"latency p50 {ms(s.get('p50_s'))} ms, p95 {ms(s.get('p95_s'))} ms; shape777 shared "
               f"{fmt(s.get('shared_dps'), 2)} dec/s ({s.get('shared_states')} states, "
               f"{fmt(s.get('shared_tokens_per_decision'), 0)} tok/dec), direct "
               f"{fmt(s.get('direct_dps'), 2)} dec/s ({s.get('direct_states')} states)",
               f"shared vs direct {s.get('sd_flips')}/{s.get('sd_rows')} flips (max Δp "
               f"{fmt(s.get('sd_max_dp'))}); stability flips reversal/wrapper/context "
               f"{s.get('flips_reversal')}/{s.get('flips_wrapper')}/{s.get('flips_context')}; "
               f"confident on missing evidence {s.get('missing_evidence_confident')}/36; "
               f"rule_application perturbed {fmt(s.get('rule_application_pert_bacc'))} "
               f"(NLL {fmt(s.get('rule_application_pert_nll'), 2)})",
               f"peak device {gib(s.get('peak_device_bytes'))}"]
        for name, a in (s.get("against") or {}).items():
            ci = a.get("ci95_authored144")
            ci = f"[{ci[0]:+.3f}, {ci[1]:+.3f}]" if isinstance(ci, list) and len(ci) == 2 else "—"
            out.append(f"vs {name}: authored144 difference {fmt(a.get('difference_authored144'))} "
                       f"{ci}, different argmax {a.get('different_argmax')}/{a.get('rows')}")
        return out
    if suite == "T9":
        return [f"accuracy {fmt(s.get('accuracy'))}, KL {fmt(s.get('kl'))}, Brier "
                f"{fmt(s.get('brier'))}, ECE {fmt(s.get('ece'))}, macro-F1 {fmt(s.get('macro_f1'))}",
                f"p50 {fmt(s.get('p50_ms'), 0)} ms/case, p95 {fmt(s.get('p95_ms'), 0)} ms, "
                f"{fmt(s.get('decisions_per_second'), 2)} dec/s",
                "by workflow: " + ", ".join(f"{k} {fmt(v)}" for k, v in (s.get("by_workflow") or {}).items())]
    return []


def telemetry_line(rec):
    p, n, r = rec["prometheus"], rec["nvidia_smi"], rec["rusage"]
    return (f"GPU avg {fmt(n.get('power_avg_w'), 1)} W (baseline "
            f"{fmt(n.get('power_baseline_w'), 1)} W), peak {fmt(n.get('power_max_w'), 1)} W, "
            f"net energy {fmt(_div(n.get('net_energy_j'), 1e3), 3)} kJ (DCGM "
            f"{fmt(_div(p.get('gpu_net_energy_j'), 1e3), 3)}), util avg "
            f"{fmt(n.get('util_avg_pct'), 0)} %, SM active {fmt(p.get('gpu_sm_active_avg'), 2)}, "
            f"DRAM active {fmt(p.get('gpu_dram_active_avg'), 2)}, VRAM max "
            f"{fmt(n.get('mem_used_max_mib'), 0)} MiB (baseline {fmt(n.get('mem_used_baseline_mib'), 0)}), "
            f"temp max {fmt(n.get('temp_max_c'), 0)} °C, power-cap throttle "
            f"{fmt(p.get('gpu_power_cap_throttle_s'), 1)} s; CPU {fmt(r.get('avg_cores'), 2)} cores avg "
            f"(host util {fmt(_pct(p.get('cpu_util_avg')), 0)} %), peak RSS "
            f"{fmt(r.get('max_rss_gib'), 2)} GiB")


def _pct(value):
    return None if value is None else value * 100


def render_research(ledger, runs):
    done_n, total, failed, elapsed, remaining, ratio = progress(ledger, runs)
    lines = [MARK_BEGIN, "", "## 11. Results log", "",
             f"Progress: **{done_n}/{total}** runs, {failed} failed; elapsed {hms(elapsed)}, "
             f"estimated remaining {hms(remaining)} (observed/estimated time: GPU "
             f"×{ratio['gpu']:.2f}, CPU ×{ratio['cpu']:.2f}). Updated "
             f"{time.strftime('%Y-%m-%d %H:%M')}.", ""]
    n = 0
    for run in runs:
        rec = ledger["runs"].get(run["id"])
        if not rec:
            continue
        n += 1
        lines += [f"### {n}. `{rec['id']}` — {SUITE_NAMES.get(run['suite'], run['suite'])} — "
                  f"{rec['status']}", "",
                  f"- {label(run)}" + (f" · {rec['threads']} threads" if rec.get("threads") else "")
                  + f" · started {rec['started']} · wall {rec['wall_s']:.1f} s "
                  f"(estimate {rec['estimate_s']:.0f} s) · exit {rec['exit_codes']}",
                  *[f"- `{c}`" for c in rec["commands"]],
                  *[f"- {line}" for line in stats_lines(rec)],
                  f"- Telemetry: {telemetry_line(rec)}"]
        if rec["status"] != "ok" or any(rec["exit_codes"]):
            lines += [f"- stderr: `{t}`" for t in rec["stderr_tail"][-5:]]
        lines.append("")
    lines.append(MARK_END)
    block = "\n".join(lines)
    text = RESEARCH_MD.read_text(encoding="utf-8")
    if MARK_BEGIN in text:
        head = text[: text.index(MARK_BEGIN)]
        tail = text[text.index(MARK_END) + len(MARK_END):] if MARK_END in text else ""
        text = head + block + tail
    else:
        text = text.rstrip("\n") + "\n\n" + block + "\n"
    RESEARCH_MD.write_text(text, encoding="utf-8")


def machine_info():
    def sh(cmd):
        try:
            return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=10).stdout.strip()
        except Exception:
            return ""
    os_name = ""
    try:
        for line in Path("/etc/os-release").read_text().splitlines():
            if line.startswith("PRETTY_NAME="):
                os_name = line.split("=", 1)[1].strip('"')
    except OSError:
        pass
    gpu = sh(["nvidia-smi", "--query-gpu=name,memory.total,driver_version,compute_cap",
              "--format=csv,noheader"])
    cpu = ""
    for line in sh(["lscpu"]).splitlines():
        if line.startswith("Model name:"):
            cpu = line.split(":", 1)[1].strip()
    mem = ""
    for line in Path("/proc/meminfo").read_text().splitlines():
        if line.startswith("MemTotal:"):
            mem = f"{int(line.split()[1]) / 2**20:.0f} GiB"
    return {
        "cpu": f"{cpu}, {os.cpu_count()} threads", "ram": mem, "gpu": gpu,
        "os": f"{os_name}, kernel {platform.release()}",
        "python": sh([str(VENV / "python"), "--version"]), "uv": sh(["uv", "--version"]),
        "commit": sh(["git", "rev-parse", "--short", "HEAD"]),
        "cuda": " / ".join(filter(None, [
            sh(["nvidia-smi", "--query-gpu=driver_version", "--format=csv,noheader"]),
            "CUDA " + (re.findall(r"CUDA[A-Za-z ]*Version:\s*([\d.]+)", sh(["nvidia-smi"])) or ["?"])[0]])),
    }


def table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return out


def render_pr(ledger, runs):
    recs = [ledger["runs"][r["id"]] for r in runs if r["id"] in ledger["runs"]]
    by = lambda pred: [r for r in recs if pred(r["run"])]  # noqa: E731
    done_n, total, failed, *_ = progress(ledger, runs)
    m = ledger.get("machine") or machine_info()
    ledger["machine"] = m
    # GitHub issue body: the title goes in the issue's title field (ISSUE_TITLE), not here.
    L = []
    if done_n < total:
        L += [f"> Status: **{done_n}/{total}** runs done — this file is regenerated after every "
              "run; the campaign is still in progress.", ""]
    if PR_SUMMARY.exists():
        L += [PR_SUMMARY.read_text(encoding="utf-8").strip(), ""]
    L += ["## Machine", ""]
    L += table(["Item", "Value"], [
        ("CPU", m["cpu"]), ("RAM", f"{m['ram']} usable — {RAM_DETAIL}"), ("GPU", m["gpu"] + " — also drives the desktop display"),
        ("Ambient temperature", AMBIENT),
        ("Driver / CUDA", m["cuda"]), ("OS", m["os"]), ("Python", m["python"] +
         " (the repo pins 3.12; `.venv` created with 3.14)"),
        ("uv", m["uv"]), ("Commit", f"`{m['commit']}`"),
        ("llama.cpp", "release `b11081`, official prebuilt packages `llama-b11081-linux-x64-cuda`, "
         "`-vulkan`, `-cpu` installed side by side"),
        ("Models", "Spark-X2.5-4B and 1.7B, XHToken's official (base) GGUF: Q8_0, Q4_K_M, BF16 — "
         "`--weights base` on `main` since 12bc7ec"),
    ])
    L += ["", "## Commands", "", "```bash",
          "uv sync --extra test --locked",
          "uv run rizzo download                                   # CUDA runtime + 4B Q8_0",
          "uv run rizzo download --only runtime --runtime vulkan",
          "uv run rizzo download --only runtime --runtime cpu",
          "uv run rizzo download --only weights --quant q4_k_m     # and bf16; and --size 1.7b for all three",
          "uv run rizzo devices                                    # also with RIZZO_LLAMA_DIR=runtimes/<package>",
          "uv run pytest -q && RIZZO_REAL=1 uv run pytest -q -m integration",
          "# per configuration (--device cuda|vulkan|cpu, --size, --quant, --kv-type, --threads):",
          "uv run rizzo decide examples/{ticket,house,numeric}.json --device D --size S --quant Q",
          "uv run rizzo evaluate benchmarks/smoke.jsonl --compare-modes --device D --size S --quant Q --output …",
          "uv run rizzo evaluate benchmarks/perturbations.jsonl --compare-modes …",
          "uv run python scripts/validate_checkpoint.py --device D --size S --quant Q --output …",
          "uv run python scripts/semif_compare.py --system rizzo --semif ../SemIf --device D --size S --quant Q --output …",
          "uv run python scripts/semif_report.py RUN --semif ../SemIf --against maintainers=results/semif-compare/…",
          "uv run python scripts/typed_decisions.py typed-decisions/all/test.jsonl --model GGUF --device D --output …",
          "```", "",
          "Every command loads the model again. Runs were strictly sequential (never two model "
          "processes at once). SemIf at `ca3ba65`, typed-decisions at `c76749e`.", ""]
    dev = by(lambda r: r["suite"] == "T2")
    if dev:
        L += ["## `rizzo devices`", ""]
        for rec in dev:
            L += [f"<details><summary>{rec['run']['package']} package: auto_selects "
                  f"<code>{rec['stats'].get('auto_selects')}</code></summary>", "", "```json",
                  json.dumps(rec["stats"].get("raw"), indent=2, ensure_ascii=False).replace(
                      str(ROOT) + "/", ""), "```", "",
                  "</details>", ""]
    tests = by(lambda r: r["suite"] in ("T0", "T1"))
    if tests:
        L += ["## Test suites", ""]
        L += table(["Suite", "Passed", "Failed", "Skipped", "Summary"], [
            (SUITE_NAMES[t["run"]["suite"]] + {"T1-integration": " (default: smallest Q8_0 on disk = 1.7B)",
                                               "T1-integration-4b": " (pinned to the 4B Q8_0)"}.get(t["id"], ""),
             t["stats"].get("passed"), t["stats"].get("failed"),
             t["stats"].get("skipped"), f"`{t['stats'].get('summary_line')}`") for t in tests])
        L += ["", "The integration suite picks the smallest Q8_0 GGUF on disk (the 1.7B once it is "
              "downloaded) and `--device auto` (CUDA here); the second row pins it to the 4B with a "
              "local pytest plugin. The 13 unit-test skips are the 6 integration tests (they need "
              "`RIZZO_REAL=1`, run separately above) and 7 MLX tests (the `mlx` extra is not installed).", ""]
    semif = by(lambda r: r["suite"] == "T7" and "batch_size" not in r["extra"])
    if semif:
        L += ["## SemIf fixtures (`scripts/semif_compare.py`)", "",
              "Balanced accuracy is the mean over families; held-out = the odd source groups "
              "(`semif_report.py`); latency is per short-state decision on a warm model. Direct mode "
              "uses 37 states (777 decisions) for the CUDA and Vulkan 4B Q8_0 and CUDA 4B BF16 rows, "
              "the script's default 3 states (63) elsewhere. Peak memory is rizzo's own "
              "`peak_device_bytes` (drop in free GPU memory) over the whole run; on the CPU, the "
              "process's peak RSS.", ""]
        rows = []
        for rec in semif:
            s = rec["stats"]
            rows.append((label(rec["run"]), fmt(s.get("authored144")), fmt(s.get("perturbations108")),
                         f"{fmt(s.get('held_out_authored144'))} / {fmt(s.get('held_out_perturbations108'))}",
                         f"{ms(s.get('p50_s'))} / {ms(s.get('p95_s'))}",
                         f"{fmt(s.get('shared_dps'), 2)} / {fmt(s.get('direct_dps'), 2)}",
                         f"{s.get('sd_flips')}/{s.get('sd_rows')}", mem_cell(rec)))
        rows += [(f"*ref* {r[0]} (maintainers)", *r[1:]) for r in REFERENCE_SEMIF]
        L += table(["Config", "authored144", "perturbations108", "held-out", "p50 / p95 ms",
                    "shape777 shared / direct dec/s", "shared vs direct flips", "peak memory"], rows)
        diffs = [(rec, name, a) for rec in semif for name, a in (rec["stats"].get("against") or {}).items()]
        if diffs:
            L += ["", "<details><summary>Paired differences on authored144 (ours − theirs, 95 % "
                  "bootstrap over source groups) and rows with a different argmax</summary>", ""]
            L += table(["Config", "Against", "Difference", "95 % CI", "Different argmax"], [
                (label(rec["run"]), name, fmt(a.get("difference_authored144")),
                 (f"[{a['ci95_authored144'][0]:+.3f}, {a['ci95_authored144'][1]:+.3f}]"
                  if isinstance(a.get("ci95_authored144"), list) else "—"),
                 f"{a.get('different_argmax')}/{a.get('rows')}") for rec, name, a in diffs])
            L += ["", "</details>"]
        L += ["", "<details><summary>Stability and weak spots</summary>", ""]
        L += table(["Config", "Flips reversal / wrapper / context", "Confident on missing evidence",
                    "rule_application perturbed (NLL)"], [
            (label(rec["run"]), f"{rec['stats'].get('flips_reversal')} / {rec['stats'].get('flips_wrapper')}"
             f" / {rec['stats'].get('flips_context')}", f"{rec['stats'].get('missing_evidence_confident')}/36",
             f"{fmt(rec['stats'].get('rule_application_pert_bacc'))} "
             f"({fmt(rec['stats'].get('rule_application_pert_nll'), 2)})") for rec in semif])
        L += ["", "</details>", ""]
    for suite, title in (("T4", "Smoke (`benchmarks/smoke.jsonl --compare-modes`)"),
                         ("T5", "Perturbations (`benchmarks/perturbations.jsonl --compare-modes`)")):
        sel = by(lambda r, s=suite: r["suite"] == s)
        if not sel:
            continue
        L += [f"## {title}", ""]
        L += table(["Config", "Accuracy", "NLL", "Brier", "ECE", "Median / p95 ms", "dec/s",
                    "Shared vs direct (max Δp)", "Peak memory"], [
            (label(r["run"]), fmt(r["stats"].get("accuracy")), fmt(r["stats"].get("nll")),
             fmt(r["stats"].get("brier")), fmt(r["stats"].get("ece")),
             f"{ms(r['stats'].get('latency_median_s'))} / {ms(r['stats'].get('latency_p95_s'))}",
             fmt(r["stats"].get("decisions_per_second"), 2),
             f"{r['stats'].get('changed_argmaxes')}/{r['stats'].get('mode_decisions')} "
             f"({fmt(r['stats'].get('max_probability_delta'), 6)})", mem_cell(r)) for r in sel])
        if suite == "T4":
            L += ["", "*ref* maintainers, 4B Q8_0 CUDA (RTX 5060 Ti): accuracy 0.95, NLL 0.459, median "
                  "66 ms. Community: M3 Pro Metal 0.95 / 0.450 / 518 ms, 0/20 changed (#5); Radeon "
                  "780M Vulkan 0.95 / 0.448 / 620 ms, 0/20 (#11); i5-1334U CPU-only Q4_K_M 0.90 / "
                  "0.685 / 11.9 s (#7)."]
        L.append("")
    sweep = by(lambda r: "batch_size" in r["extra"])
    if sweep:
        L += ["## Batch-size sweep (`semif_compare.py --batch-size N --direct-states 0`, 4B Q8_0)", ""]
        L += table(["Config", "shape777 shared dec/s", "Peak memory", "Wall s"], [
            (label(r["run"]), fmt(r["stats"].get("shared_dps"), 2), mem_cell(r), fmt(r["wall_s"], 0))
            for r in sweep])
        L.append("")
    typed = by(lambda r: r["suite"] == "T9")
    if typed:
        L += ["## typed-decisions (`scripts/typed_decisions.py`, 400 test cases, zero-shot)", ""]
        L += table(["Config", "Accuracy", "KL", "Brier", "ECE", "p50 / p95 ms per case", "dec/s"], [
            (label(r["run"]), fmt(r["stats"].get("accuracy")), fmt(r["stats"].get("kl")),
             fmt(r["stats"].get("brier")), fmt(r["stats"].get("ece")),
             f"{fmt(r['stats'].get('p50_ms'), 0)} / {fmt(r['stats'].get('p95_ms'), 0)}",
             fmt(r["stats"].get("decisions_per_second"), 2)) for r in typed])
        L += ["", "*ref* maintainers (docs/training.md, RTX 5060 Ti): 4B Q8_0 0.574 / KL 2.899 / Brier "
              "0.480 / 201 ms; 4B BF16 0.574 / 2.935 / 0.479 / 250 ms.", ""]
    val = by(lambda r: r["suite"] == "T6")
    if val:
        L += ["## `scripts/validate_checkpoint.py`", ""]
        L += table(["Config", "Smoke acc (NLL)", "Long state shared / direct ms", "Long state changed",
                    "Load s", "Peak memory"], [
            (label(r["run"]), f"{fmt(r['stats'].get('smoke_accuracy'))} ({fmt(r['stats'].get('smoke_nll'))})",
             f"{ms(r['stats'].get('long_shared_s'))} / {ms(r['stats'].get('long_direct_s'))}",
             r["stats"].get("long_changed_argmaxes"), fmt(g(r, "stats.model.load_seconds"), 1),
             gib(r["stats"].get("peak_device_bytes")) if r["run"]["device"] != "cpu"
             else f"RSS {r['rusage']['max_rss_gib']:.2f} GiB") for r in val])
        L.append("")
    dec = by(lambda r: r["suite"] == "T3")
    if dec:
        L += ["## `rizzo decide examples/*.json`", ""]
        rows = []
        for r in dec:
            t = r["stats"].get("ticket", {})
            answers = ", ".join(f"{q}={a['value']}" if a["status"] == "ok" else f"{q}: {a['status']}"
                                for q, a in (t.get("answers") or {}).items())
            rows.append((label(r["run"]), answers or "—",
                         " / ".join(ms(r["stats"].get(n, {}).get("total_s")) for n in ("ticket", "house", "numeric"))))
        L += table(["Config", "ticket.json answers", "ticket / house / numeric ms"], rows)
        L.append("")
    if recs:
        L += ["## Telemetry per run", "",
              "GPU: `nvidia-smi` at 100 ms (power, energy, memory, utilization, temperature) and "
              "DCGM at 1 s (SM activity; runs of 5 s or more); CPU: the child's rusage. Net energy = "
              "integral of GPU power over the run − 10 s idle baseline power × duration; each window "
              "covers the whole command, model loading included. The GPU also drives the desktop, so "
              "the baseline is not zero.", "",
              "<details><summary>Table</summary>", ""]
        L += table(["Run", "Wall s", "GPU avg / peak W", "Net GPU kJ", "GPU util %", "VRAM max MiB",
                    "SM active", "Temp max °C", "CPU cores avg", "Peak RSS GiB"], [
            (label(r["run"]) + f" · {SUITE_NAMES.get(r['run']['suite'])}", fmt(r["wall_s"], 1),
             f"{fmt(r['nvidia_smi'].get('power_avg_w'), 0)} / {fmt(r['nvidia_smi'].get('power_max_w'), 0)}",
             fmt(_div(r["nvidia_smi"].get("net_energy_j"), 1e3), 3) if r["run"].get("device") != "cpu"
             else "— (GPU idle)",
             fmt(r["nvidia_smi"].get("util_avg_pct"), 0), fmt(r["nvidia_smi"].get("mem_used_max_mib"), 0),
             fmt(r["prometheus"].get("gpu_sm_active_avg"), 2), fmt(r["nvidia_smi"].get("temp_max_c"), 0),
             fmt(r["rusage"].get("avg_cores"), 2), fmt(r["rusage"].get("max_rss_gib"), 2)) for r in recs])
        L += ["", "</details>", ""]
    odd = [r for r in recs if r["status"] != "ok" or (any(r["exit_codes"])
                                                     and r["run"]["suite"] not in ("T0", "T1"))]
    L += ["## Anything odd", ""]
    L += ["- With `--threads` unset, llama.cpp's C API default is 4 threads "
          "(`llama_context_default_params().n_threads == 4`), so CPU runs use 4 of the 32 "
          "threads unless `--threads` is given; see the threads rows in the smoke table. The CPU "
          "runs after that sweep use the fastest explicit count."]
    for r in recs:
        for test in r["stats"].get("failed_tests") or []:
            L.append(f"- {SUITE_NAMES[r['run']['suite']]} (`{r['id']}`): `{test}` failed.")
    for r in odd:
        L.append(f"- `{r['id']}`: status {r['status']}, exit codes {r['exit_codes']}"
                 + (f"; stderr: `{redact(r['stderr_tail'][-1])}`" if r["stderr_tail"] else ""))
    if PR_NOTES.exists():
        L += [PR_NOTES.read_text(encoding="utf-8").strip()]
    L.append("")
    PR_MD.write_text("\n".join(L), encoding="utf-8")


def render(ledger, runs):
    render_research(ledger, runs)
    render_pr(ledger, runs)
    save_ledger(ledger)


# ----------------------------------------------------------------------------- main

def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--render", action="store_true")
    parser.add_argument("--reextract", action="store_true",
                        help="recompute stats of finished runs from their files, then render")
    parser.add_argument("--only", help="comma-separated substrings of run ids")
    parser.add_argument("--limit", type=int)
    args = parser.parse_args()
    runs = plan()
    ledger = load_ledger()
    todo = [r for r in runs if r["id"] not in ledger["runs"]]
    if args.only:
        keys = args.only.split(",")
        todo = [r for r in todo if any(k in r["id"] for k in keys)]
    if args.limit:
        todo = todo[: args.limit]
    if args.dry_run:
        total = 0
        for r in todo:
            total += estimate(r)
            print(f"{r['id']:45s} {r['block']:8s} ~{estimate(r):6.0f}s  "
                  + " ; ".join(" ".join(_short(a) for a in c[0]) for c in commands(r, OUT / r["id"], ledger)))
        print(f"{len(todo)} runs, ~{hms(total)} (plan has {len(runs)} runs)")
        return
    if args.reextract:
        by_id = {r["id"]: r for r in runs}
        for rid, rec in ledger["runs"].items():
            rundir = OUT / rid
            outputs = {f.stem: f.read_text(encoding="utf-8", errors="replace")
                       for f in rundir.glob("*.stdout")}
            rec["stats"] = extract(by_id.get(rid, rec["run"]), rundir, outputs)
            sampler = Sampler.__new__(Sampler)
            sampler.path = rundir / "nvidia-smi.csv"
            rec["nvidia_smi"] = sampler.summary(rec["t0"], rec["t1"], rec["b0"], rec["b1"])
            rec["prometheus"] = prometheus_stats(rec["t0"], rec["t1"], rec["b0"], rec["b1"])
            rec["stderr_tail"] = [redact(line) for line in rec.get("stderr_tail", [])]
        ledger.pop("machine", None)
    if args.render or args.reextract:
        render(ledger, runs)
        return
    OUT.mkdir(parents=True, exist_ok=True)
    check = subprocess.run(
        [str(VENV / "python"), "-c", "from rizzo_flow import llama_release as r; "
         "print(*(r.locate(f).name for f in ('cuda', 'vulkan', 'cpu')))"],
        cwd=ROOT, capture_output=True, text=True)
    names = check.stdout.split()
    for family, name in zip(("cuda", "vulkan", "cpu"), names):
        if not name.endswith(f"-{family}"):
            raise SystemExit(f"--device {family} would load {name}: install the {family} package")
    if len(names) != 3:
        raise SystemExit(f"runtime check failed: {check.stderr.strip()}")

    def stop(signum, frame):
        raise KeyboardInterrupt(f"signal {signum}")

    signal.signal(signal.SIGTERM, stop)
    for run in todo:
        print(f"[{time.strftime('%H:%M:%S')}] start {run['id']}", flush=True)
        record = execute(run, ledger)
        ledger["runs"][run["id"]] = record
        save_ledger(ledger)  # the measurement is safe even if rendering fails below
        try:
            render(ledger, runs)
        except Exception as error:  # a report bug must not stop a 10 h campaign
            with open(CAMPAIGN / "errors.log", "a", encoding="utf-8") as log:
                log.write(f"{time.strftime('%F %T')} render after {run['id']}: {error!r}\n")
        print(f"[{time.strftime('%H:%M:%S')}] done  {run['id']} {record['status']} "
              f"{record['wall_s']:.1f}s exit {record['exit_codes']}", flush=True)


if __name__ == "__main__":
    main()
